# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/mypaceshun/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: autopep8
    -   id: autoflake
    -   id: isort
    -   id: flake8
