name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  test:
    uses: .github/workflows/test.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Update pip
        run: pip install -U pip setuptools wheel
      - name: Install poetry
        run: pip install poetry poetry-dynamic-versioning
      - name: Install dependent libraries
        run: poetry install
      - name: Build package
        run: poetry build
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          path: 'dist'
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
